KaneKidsBanking.Web/Pages/Account/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KaneKidsBanking.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KaneKidsBanking.Web.Accounts
{
    public class IndexModel : PageModel
    {

        

        public IndexModel(CosmosDb db)
        {
            this.Db = db;
        }

        public List<KaneKidsBanking.Database.Account> Accounts { get; private set; }
        private CosmosDb Db { get; }

        public void OnGet()
        {
            this.Accounts = Db.GetAccounts();
        }
    }
}

KaneKidsBanking.Web/Pages/Account/Transactions.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KaneKidsBanking.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Azure.Cosmos.Linq;

namespace KaneKidsBanking.Web.Pages.Account
{
    public class TransactionsModel : PageModel
    {

        public TransactionsModel(CosmosDb db)
        {
            this.Db = db;
        }

        public CosmosDb Db { get; }
        public Database.Account Account { get; private set; }
        public IOrderedEnumerable<Transaction> Transactions { get; private set; }

        public void OnGet(string Id)
        {
            GetItems(Id);
        }

        private void GetItems(string Id)
        {
            this.Account = this.Db.GetAccountByName(Id);
            this.Transactions = this.Account.Transactions.OrderByDescending(c => c.TransDate);
        }

        public ActionResult OnPostDelete(string Id, string TransactionId)
        {
            this.Account = this.Db.GetAccountByName(Id);
            this.Account.RemoveTransaction(TransactionId);
            this.Db.UpsertAccount(this.Account);
            return this.RedirectToPage("./Transactions", new { Id = Id });
            //this.GetItems(Id);
        }

        public ActionResult OnPostSave(string Id)
        {
            // Get Account
            this.Account = this.Db.GetAccountByName(Id);

            if (!String.IsNullOrEmpty(Request.Form["edit-guid"]))
            {
                // Update
                this.Account = this.Db.GetAccountByName(Id);
                var transItem = this.Account.Transactions.Where(c => c.TransactionId.ToString() == Request.Form["edit-guid"]).FirstOrDefault();
                SetTransactionFromForm(transItem);
            }
            else
            {
                // Insert
                var transItem = new Transaction();
                transItem.TransactionId = System.Guid.NewGuid();
                SetTransactionFromForm(transItem);
                this.Account.InsertTransaction(transItem);
            }

            // Save
            this.Db.UpsertAccount(this.Account);

            // Redirect
            return this.RedirectToPage("./Transactions", new { Id = Id });
        }

        private void SetTransactionFromForm(Transaction transItem)
        {
            transItem.Name = Request.Form["edit-name"].ToString();
            transItem.TransDate = Convert.ToDateTime(Request.Form["edit-date"]);
            transItem.Amount = Convert.ToDecimal(Request.Form["edit-amount"]);
        }
    }
}

KaneKidsBanking.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace KaneKidsBanking.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

KaneKidsBanking.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace KaneKidsBanking.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, IConfiguration configuration)
        {
            _logger = logger;
            Configuration = configuration;
        }

        public void OnGet()
        {

        }

        [BindProperty]
        public string UserName { get; set; }
        [BindProperty, DataType(DataType.Password)]
        public string Password { get; set; }
        public string Message { get; set; }
        public IConfiguration Configuration { get; }

        public class SiteUser
        {
            public string UserName { get; set; }
            public string Password { get; set; }
        }

        public async Task<IActionResult> OnPost()
        {
            
            var users = Configuration.GetSection("SiteUsers").Get<SiteUser[]>();

            if (users.Where(c => c.UserName.ToUpper() == UserName.ToUpper() && c.Password == Password).Count() == 1)
            {

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, UserName)
                };
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                return RedirectToPage("/Account/Index");           
            }
            
            Message = "Invalid attempt";
            return Page();
        }
    }
}

KaneKidsBanking.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace KaneKidsBanking.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

KaneKidsBanking.Web/Pages/Account/Index.cshtml
@page
@model KaneKidsBanking.Web.Accounts.IndexModel
@{

    this.ViewData["Title"] = "List of Accounts";
}
<h1>List of Accounts</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Balance</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var account in Model.Accounts)
        {
        <tr>
            <td>@account.AccountId</td>
            <td>@account.Balance().ToString("c")</td>
            <td><a asp-area="" asp-page="./Transactions" asp-route-ID="@account.AccountId">Open Account</a></td>
        </tr>
        }
    </tbody>
</table>

KaneKidsBanking.Web/Pages/Account/Transactions.cshtml
@page
@model KaneKidsBanking.Web.Pages.Account.TransactionsModel
@{

    this.ViewData["Title"] = "Account " + Model.Account.Id;
}
<h1>Account @Model.Account.Id</h1>
<h2>Balance @Model.Account.Balance().ToString("c")</h2>
<br />
<h2>
    Transactions History  <button onclick="return InsertItem()" class="btn btn-piggybank btn-sm">New Record</button>
</h2>
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Amount</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var trans in Model.Transactions)
            {
                <tr>
                    <td><label class="trans-item-guid" style="display: none">@trans.TransactionId</label><label class="trans-item-name">@trans.Name</label></td>
                    <td><label class="trans-item-date">@trans.TransDate.ToShortDateString()</label></td>
                    <td>@trans.Amount.ToString("c")<label style="display: none" class="trans-item-amount">@trans.Amount</label></td>
                    <td>
                        <button onclick="return EditCurrentItem(this)" class="btn btn-piggybank btn-sm">Edit</button>
                        <button onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger btn-sm" asp-page-handler="Delete" asp-route-id="@Model.Account.AccountId" asp-route-transactionId="@trans.TransactionId">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div id="edit-form" style="display: none">
        <h2>Edit Transaction</h2>
        <table>
            <tr style="display: none">
                <td>GUID</td>
                <td><input type="text" name="edit-guid" id="edit-guid" /></td>
            </tr>
            <tr>
                <td>Name</td>
                <td><input type="text" name="edit-name" id="edit-name" /></td>
            </tr>
            <tr>
                <td>Date</td>
                <td><input type="text" name="edit-date" id="edit-date" /></td>
            </tr>
            <tr>
                <td>Amount</td>
                <td><input type="text" name="edit-amount" id="edit-amount" /></td>
            </tr>
            <tr>
                <td></td>
                <td><button class="btn btn-piggybank btn-sm" asp-page-handler="Save" asp-route-id="@Model.Account.AccountId">Save</button></td>
            </tr>
        </table>
    </div>
    <div>
        <button class="btn btn-piggybank btn-sm" onclick="window.location.href = './Index'; return false;">List of Accounts</button>
    </div>

</form>

KaneKidsBanking.Web/Pages/Index.cshtml
@page
@model KaneKidsBanking.Web.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}
<form method="post">
    <div class="text-center">
        <h1 class="display-4">Welcome to Kids Bank</h1>
        <br />
        <h2>Login</h2>
        <div class="container">

            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-3">Username</div>
                <div class="col-md-3"><input type="text" name="Username" /></div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-3">Password</div>
                <div class="col-md-3"><input type="password" name="Password" /></div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
                <div class="col-md-3"><button asp-page-handler="Login" asp-area="" class="btn btn-piggybank btn-sm">Login</button></div>
                <div class="col-md-3">@Model.Message</div>
            </div>

        </div>
    </div>
</form>
<script>
    //window.location.href = "../Account/Index"
</script>

KaneKidsBanking.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KaneKidsBanking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 header-style">
            <div class="container-fluid">
                <div class="row row-full">
                    <div class="col-md-2 header-icon-cell">
                        <img src="~/images/Piggybank.png" class="header-icon"/>
                    </div>
                    <div class="col-md-10">
                        <a class="navbar-brand header-text" asp-area="" asp-page="/Account/Index">Kids Bank</a>
                        <!--
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-page="/Account/Index">Accounts</a>
                                </li>
                            </ul>
                        </div>
                        -->
                    </div>
                    
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>